//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace medicalForm
{


     public partial class Default
     {

          /// <summary>
          /// form1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlForm form1;

          /// <summary>
          /// Label11 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label11;

          /// <summary>
          /// Label10 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label10;

          /// <summary>
          /// Label2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label2;

          /// <summary>
          /// TextBox8 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox8;

          /// <summary>
          /// RflVal control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal;

          /// <summary>
          /// Label3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label3;

          /// <summary>
          /// TextBox2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox2;

          /// <summary>
          /// RflVal0 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal0;

          /// <summary>
          /// Label4 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label4;

          /// <summary>
          /// TextBox3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox3;

          /// <summary>
          /// TextBox9 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox9;

          /// <summary>
          /// RflVal2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal2;

          /// <summary>
          /// TextBox10 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox10;

          /// <summary>
          /// RflVal3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal3;

          /// <summary>
          /// DropDownList1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.DropDownList DropDownList1;

          /// <summary>
          /// RflVal4 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal4;

          /// <summary>
          /// TextBox7 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox7;

          /// <summary>
          /// RflVal5 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal5;

          /// <summary>
          /// Label5 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label5;

          /// <summary>
          /// TextBox25 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox25;

          /// <summary>
          /// RegularExpressionValidator4 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator4;

          /// <summary>
          /// TextBox11 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox11;

          /// <summary>
          /// RegularExpressionValidator2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator2;

          /// <summary>
          /// TextBox12 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox12;

          /// <summary>
          /// ImageButton1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.ImageButton ImageButton1;

          /// <summary>
          /// Calendar1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Calendar Calendar1;

          /// <summary>
          /// TextBox13 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox13;

          /// <summary>
          /// RflVal9 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal9;

          /// <summary>
          /// RadioButton5 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RadioButton RadioButton5;

          /// <summary>
          /// RadioButton6 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RadioButton RadioButton6;

          /// <summary>
          /// RadioButton4 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RadioButton RadioButton4;

          /// <summary>
          /// TextBox15 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox15;

          /// <summary>
          /// RflVal11 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal11;

          /// <summary>
          /// TextBox16 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox16;

          /// <summary>
          /// RflVal13 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal13;

          /// <summary>
          /// TextBox24 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox24;

          /// <summary>
          /// RflVal12 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal12;

          /// <summary>
          /// TextBox17 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox17;

          /// <summary>
          /// RflVal14 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal14;

          /// <summary>
          /// TextBox20 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox20;

          /// <summary>
          /// RegularExpressionValidator7 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator7;

          /// <summary>
          /// TextBox18 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox18;

          /// <summary>
          /// RegularExpressionValidator3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator3;

          /// <summary>
          /// TextBox21 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox21;

          /// <summary>
          /// RegularExpressionValidator6 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator6;

          /// <summary>
          /// TextBox22 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox22;

          /// <summary>
          /// RflVal17 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal17;

          /// <summary>
          /// TextBox23 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox23;

          /// <summary>
          /// RegularExpressionValidator5 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator5;

          /// <summary>
          /// Label12 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label12;

          /// <summary>
          /// RadioButton7 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RadioButton RadioButton7;

          /// <summary>
          /// RadioButton8 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RadioButton RadioButton8;

          /// <summary>
          /// RadioButton9 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RadioButton RadioButton9;

          /// <summary>
          /// RadioButton10 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RadioButton RadioButton10;

          /// <summary>
          /// TextBox46 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox46;

          /// <summary>
          /// Label13 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label13;

          /// <summary>
          /// TextBox26 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox26;

          /// <summary>
          /// RflVal18 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal18;

          /// <summary>
          /// Label14 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label14;

          /// <summary>
          /// TextBox27 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox27;

          /// <summary>
          /// RflVal19 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal19;

          /// <summary>
          /// Label15 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label15;

          /// <summary>
          /// TextBox28 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox28;

          /// <summary>
          /// TextBox29 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox29;

          /// <summary>
          /// RflVal21 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal21;

          /// <summary>
          /// TextBox30 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox30;

          /// <summary>
          /// RflVal22 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal22;

          /// <summary>
          /// DropDownList2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.DropDownList DropDownList2;

          /// <summary>
          /// RflVal23 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal23;

          /// <summary>
          /// TextBox31 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox31;

          /// <summary>
          /// RflVal24 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal24;

          /// <summary>
          /// Label16 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label16;

          /// <summary>
          /// TextBox32 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox32;

          /// <summary>
          /// RegularExpressionValidator8 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator8;

          /// <summary>
          /// TextBox33 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox33;

          /// <summary>
          /// RegularExpressionValidator9 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator9;

          /// <summary>
          /// TextBox34 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox34;

          /// <summary>
          /// ImageButton2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.ImageButton ImageButton2;

          /// <summary>
          /// Calendar2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Calendar Calendar2;

          /// <summary>
          /// TextBox35 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox35;

          /// <summary>
          /// RflVal25 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal25;

          /// <summary>
          /// RadioButton11 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RadioButton RadioButton11;

          /// <summary>
          /// RadioButton12 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RadioButton RadioButton12;

          /// <summary>
          /// RadioButton13 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RadioButton RadioButton13;

          /// <summary>
          /// TextBox39 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox39;

          /// <summary>
          /// RflVal29 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal29;

          /// <summary>
          /// TextBox40 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox40;

          /// <summary>
          /// RflVal30 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal30;

          /// <summary>
          /// TextBox41 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox41;

          /// <summary>
          /// RegularExpressionValidator10 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator10;

          /// <summary>
          /// TextBox42 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox42;

          /// <summary>
          /// RegularExpressionValidator11 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator11;

          /// <summary>
          /// TextBox43 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox43;

          /// <summary>
          /// RegularExpressionValidator12 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator12;

          /// <summary>
          /// Label17 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label17;

          /// <summary>
          /// Label18 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label18;

          /// <summary>
          /// TextBox48 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox48;

          /// <summary>
          /// RflVal31 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal31;

          /// <summary>
          /// TextBox49 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox49;

          /// <summary>
          /// TextBox51 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox51;

          /// <summary>
          /// RflVal33 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal33;

          /// <summary>
          /// TextBox52 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox52;

          /// <summary>
          /// RflVal34 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal34;

          /// <summary>
          /// DropDownList3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.DropDownList DropDownList3;

          /// <summary>
          /// RflVal35 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal35;

          /// <summary>
          /// TextBox53 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox53;

          /// <summary>
          /// RflVal36 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal36;

          /// <summary>
          /// Label21 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label21;

          /// <summary>
          /// TextBox54 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox54;

          /// <summary>
          /// RegularExpressionValidator13 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator13;

          /// <summary>
          /// TextBox55 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox55;

          /// <summary>
          /// RegularExpressionValidator14 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator14;

          /// <summary>
          /// TextBox56 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox56;

          /// <summary>
          /// ImageButton3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.ImageButton ImageButton3;

          /// <summary>
          /// Calendar3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Calendar Calendar3;

          /// <summary>
          /// TextBox57 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox57;

          /// <summary>
          /// RflVal37 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal37;

          /// <summary>
          /// TextBox58 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox58;

          /// <summary>
          /// RflVal45 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal45;

          /// <summary>
          /// TextBox59 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox59;

          /// <summary>
          /// RflVal44 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal44;

          /// <summary>
          /// Label23 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label23;

          /// <summary>
          /// TextBox60 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox60;

          /// <summary>
          /// RflVal38 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal38;

          /// <summary>
          /// TextBox61 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox61;

          /// <summary>
          /// RflVal46 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal46;

          /// <summary>
          /// TextBox62 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox62;

          /// <summary>
          /// RflVal39 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal39;

          /// <summary>
          /// TextBox63 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox63;

          /// <summary>
          /// RflVal40 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal40;

          /// <summary>
          /// DropDownList4 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.DropDownList DropDownList4;

          /// <summary>
          /// RflVal41 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal41;

          /// <summary>
          /// TextBox64 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox64;

          /// <summary>
          /// RflVal42 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal42;

          /// <summary>
          /// Label24 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label Label24;

          /// <summary>
          /// TextBox65 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox65;

          /// <summary>
          /// RegularExpressionValidator15 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator15;

          /// <summary>
          /// TextBox66 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox66;

          /// <summary>
          /// RegularExpressionValidator16 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator16;

          /// <summary>
          /// TextBox67 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox67;

          /// <summary>
          /// ImageButton4 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.ImageButton ImageButton4;

          /// <summary>
          /// Calendar4 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Calendar Calendar4;

          /// <summary>
          /// TextBox68 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox68;

          /// <summary>
          /// RflVal43 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal43;

          /// <summary>
          /// TextBox69 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox69;

          /// <summary>
          /// RflVal47 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal47;

          /// <summary>
          /// TextBox70 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox TextBox70;

          /// <summary>
          /// RflVal48 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator RflVal48;

          /// <summary>
          /// btnSubmit control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button btnSubmit;
     }
}
